export const Users = [
    {
      id:1,
      profilePicture:"https://i.ibb.co/c6xjTVS/pexels-marcelo-chagas-6347176.jpg",
      username: "Kasun Gayantha",
    },
    {
      id:2,
      profilePicture: "https://i.ibb.co/N1N6Hnd/add1b55d-63d3-4fc3-8ff6-92bdaecf7973.png",
      username: "Neluni Priyangika",
    },
    {
      id:3,
      profilePicture:"https://i.ibb.co/TbVYd6d/pexels-ketut-subiyanto-4307869.jpg",
      username: "Chamith Gayantha",
    },
    {
      id:4,
      profilePicture: "https://i.ibb.co/YBDPRWb/pexels-nagy-szabi-4134204.jpg",
      username: "Madura Sirisena",
    },
    {
      id:5,
      profilePicture: "https://i.ibb.co/vLsSK4s/pexels-marlon-schmeiski-3839910.jpg",
      username: "chathuri Rajapaksha",
    },
    {
      id:6,
      profilePicture: "https://i.ibb.co/c6xjTVS/pexels-marcelo-chagas-6347176.jpg",
      username: "Sunil Perera ",
    },
    {
      id:7,
      profilePicture:"https://i.ibb.co/mvLnTpj/pexels-juan-vargas-6267570.jpg",
      username: "Yohani Samaradiwakara",
    },
    {
      id:8,
      profilePicture: "https://i.ibb.co/TbVYd6d/pexels-ketut-subiyanto-4307869.jpg",
      username: "Wimal Wirawansha",
    },
    {
      id:9,
      profilePicture: "https://i.ibb.co/YBDPRWb/pexels-nagy-szabi-4134204.jpg",
      username: "Priyantha Disanayake",
    },
    {
      id:10,
      profilePicture: "https://i.ibb.co/YBDPRWb/pexels-nagy-szabi-4134204.jpg",
      username: "Saliya Perera ",
    }
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Successfully completed the Programming in Python - 1",
      photo: "https://i.ibb.co/XWLj2bg/1679200049046.jpg",
      page:">  Post",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
      description:"I am excited 🤩 to share that I have successfully completed the Programming in Python - 1. Python for Beginners course offered by UOM! This course has equipped me with fundamental programming concepts, data types, and control structures in Python, which has helped me develop the skills to create simple Python programs. I am proud to have earned my certificate and look forward to applying my newfound knowledge in my future endeavours."
    },
    {
      id: 2,
      desc:"Are you ready to dive into the future of DevOps?",
      photo: "https://i.ibb.co/kSDB5Hn/1681453213831.jpg",
      page:">  Post",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
      description:"Let's talk about DevOps 2.0.This isn't just a minor upgrade! DevOps 2.0 is a complete game-changer. It's all about automating every aspect of the software development process, from testing to deployment."+
      " But is automation the key to success, or are we in danger of losing the human touch? Next, let's take a look at serverless computing."+
      "No, it's not a world without servers, but rather a way to build and run applications without the need for dedicated servers. But will this new approach to computing lead to a new era of innovation, or will it create new security challenges?",
    },
    {
      id: 3,
      desc: "What is DevOps and why is it important in modern software development?",
      page:">  Discussion Portal",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
      description:"DevOps has emerged as a popular approach in software development. Could you provide an overview of what DevOps is and explain its significance in the context of modern software development practices?"
    },
    {
      id: 4,
      desc: "What are the key principles of DevOps?",
      page:">  Discussion Portal",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
      description: "I've been hearing a lot about DevOps and its principles. Can you please shed some light on the fundamental principles that underpin DevOps methodologies and how they contribute to efficient software delivery?",
    },
    {
      id: 5,
      desc:"DevOps: Optimizing Software Development and Delivery",
      photo: "https://i.ibb.co/Qm0dXMk/ADO-Dev-Ops-Tool-1200x675-2x.png",
      page:">  Post",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
      description: "Technology is advancing rapidly, and software development is no exception. As an IT student, I have seen firsthand the challenges of delivering high-quality software quickly and efficiently. That's why I explored the world of DevOps, a methodology that aims to streamline the software development lifecycle and improve collaboration between development and operations teams. In this article, I'll share my understanding of what DevOps is, why it's important, and how it can benefit your organization.",
    },
    {
      id: 6,
      desc:"Successfully completed the 'Introduction to DevOps' course",
      photo: "https://i.ibb.co/C6qHcQK/Capture1.jpg",
      page:">  Post",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
      description:"Hi all, I have successfully completed the 'Introduction to DevOps' course. It helps me to Understand containerization, Docker, Jenkins, & continuous monitoring. This this Perfect for beginners. ",
    },
    {
      id: 7,
      desc: "How does DevOps facilitate collaboration between development and operations teams?",
      page:">  Discussion Portal",
      description:"I've heard that DevOps helps improve collaboration between development and operations teams. Could you explain how DevOps practices and methodologies bridge the gap between these two traditionally separate teams and foster a culture of collaboration?",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      desc:"Successfully completed 😍 ❤ The course on DevOps best practices for Docker with Jenkins",
      photo: "https://i.ibb.co/88khVyT/Capture2.jpg",
      page:">  Post",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
      description:"",
    },
    {
      id: 9,
      desc: "What are some common tools used in a DevOps environment?",
      page:">  Discussion Portal",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
      description:"As I delve into the world of DevOps, I'm curious about the tools that are commonly utilized. Could you provide some insights into the popular tools and technologies employed in a typical DevOps environment and their respective purposes?",
    },
    {
      id: 10,
      desc:"What are the benefits of implementing DevOps in an organization?",
      page:">  Discussion Portal",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
      description:"I'm interested in understanding the tangible benefits that organizations can expect to gain from adopting DevOps practices. Could you outline some of the advantages and positive outcomes that organizations can experience by implementing DevOps?",
    }
  ];